cls
@echo on

set lib_path=J:\Programmations\java\librairies
set lwjgl_path=%lib_path%\LWJGL
set natives_path=%lwjgl_path%\natives
set lombok_path=%lib_path%\archives\Lombok\lombok-1.18.26.jar

set modules_path=%lombok_path%;%lwjgl_path%\lwjglx-debug-1.0.0.jar;J:\Programmations\java\eclipse\moteurs\OnsieaEngine2\common;J:\Programmations\java\eclipse\tools\OnseaLogger\bin;J:\Programmations\java\librairies\mslinks-1.1.0.jar;J:\Programmations\java\librairies\JNA\jna-5.5.0.jar;J:\Programmations\java\librairies\JNA\jna-platform-5.5.0.jar;%lwjgl_path%\lwjgl3-awt-0.1.8.jar;%lwjgl_path%\lwjgl-freetype.jar;%lwjgl_path%\lwjgl-jemalloc.jar;%lwjgl_path%\lwjgl-nanovg.jar;%lwjgl_path%\lwjgl-egl.jar;%lwjgl_path%\lwjgl-vma.jar;%lwjgl_path%\lwjgl-assimp.jar;%lwjgl_path%\lwjgl-harfbuzz.jar;%lwjgl_path%\lwjgl-par.jar;%lwjgl_path%\lwjgl-stb.jar;%lwjgl_path%\lwjgl-openal.jar;%lwjgl_path%\lwjgl-zstd.jar;%lwjgl_path%\lwjgl-vulkan.jar;%lwjgl_path%\lwjgl-yoga.jar;%lwjgl_path%\lwjgl-glfw.jar;%lwjgl_path%\lwjgl-openxr.jar;%lwjgl_path%\lwjgl-llvm.jar;%lwjgl_path%\steamworks4j-1.9.0.jar;%lwjgl_path%\lwjgl-cuda.jar;%lwjgl_path%\lwjgl-meshoptimizer.jar;%lwjgl_path%\lwjgl-ovr.jar;%lwjgl_path%\lwjgl-lmdb.jar;%lwjgl_path%\lwjgl-remotery.jar;%lwjgl_path%\lwjgl-opus.jar;%lwjgl_path%\lwjgl-xxhash.jar;%lwjgl_path%\lwjgl-nuklear.jar;%lwjgl_path%\lwjgl-spvc.jar;%lwjgl_path%\lwjgl-sse.jar;%lwjgl_path%\lwjgl-fmod.jar;%lwjgl_path%\steamworks4j-server-1.9.0.jar;%lwjgl_path%\lwjgl-odbc.jar;%lwjgl_path%\lwjgl-bgfx.jar;%lwjgl_path%\lwjgl-jawt.jar;%lwjgl_path%\lwjgl-shaderc.jar;%lwjgl_path%\lwjgl.jar;%lwjgl_path%\lwjgl-tootle.jar;%lwjgl_path%\lwjgl-tinyfd.jar;%lwjgl_path%\lwjgl-opencl.jar;%lwjgl_path%\lwjgl-opengl.jar;%lwjgl_path%\lwjgl-lz4.jar;%lwjgl_path%\lwjgl-libdivide.jar;%lwjgl_path%\lwjgl-openvr.jar;%lwjgl_path%\lwjgl-opengles.jar;%lwjgl_path%\lwjgl-tinyexr.jar;%lwjgl_path%\lwjgl-nfd.jar;%lwjgl_path%\lwjgl-meow.jar;%lwjgl_path%\lwjgl-ktx.jar;%lwjgl_path%\joml-1.10.5.jar;%lwjgl_path%\lwjgl-rpmalloc.jar
set classes_path=%natives_path%\lwjgl-vma-natives-windows.jar;%natives_path%\lwjgl-opengl-natives-windows.jar;%natives_path%\lwjgl-nuklear-natives-windows.jar;%natives_path%\lwjgl-glfw-natives-windows.jar;%natives_path%\lwjgl-tootle-natives-windows.jar;%natives_path%\lwjgl-ovr-natives-windows.jar;%natives_path%\lwjgl-stb-natives-windows.jar;%natives_path%\lwjgl-opus-natives-windows.jar;%natives_path%\lwjgl-assimp-natives-windows.jar;%natives_path%\lwjgl-opengles-natives-windows.jar;%natives_path%\lwjgl-nanovg-natives-windows.jar;%natives_path%\lwjgl-xxhash-natives-windows.jar;%natives_path%\lwjgl-remotery-natives-windows.jar;%natives_path%\lwjgl-meshoptimizer-natives-windows.jar;%natives_path%\lwjgl-tinyfd-natives-windows.jar;%natives_path%\lwjgl-yoga-natives-windows.jar;%natives_path%\lwjgl-lmdb-natives-windows.jar;%natives_path%\lwjgl-nfd-natives-windows.jar;%natives_path%\lwjgl-meow-natives-windows.jar;%natives_path%\lwjgl-openvr-natives-windows.jar;%natives_path%\lwjgl-lz4-natives-windows.jar;%natives_path%\lwjgl-rpmalloc-natives-windows.jar;%natives_path%\lwjgl-spvc-natives-windows.jar;%natives_path%\lwjgl-freetype-natives-windows.jar;%natives_path%\lwjgl-llvm-natives-windows.jar;%natives_path%\lwjgl-openal-natives-windows.jar;%natives_path%\lwjgl-harfbuzz-natives-windows.jar;%natives_path%\lwjgl-shaderc-natives-windows.jar;%natives_path%\lwjgl-bgfx-natives-windows.jar;%natives_path%\lwjgl-tinyexr-natives-windows.jar;%natives_path%\lwjgl-natives-windows.jar;%natives_path%\lwjgl-openxr-natives-windows.jar;%natives_path%\lwjgl-jemalloc-natives-windows.jar;%natives_path%\lwjgl-sse-natives-windows.jar;%natives_path%\lwjgl-zstd-natives-windows.jar;%natives_path%\lwjgl-ktx-natives-windows.jar;%natives_path%\lwjgl-libdivide-natives-windows.jar;%natives_path%\lwjgl-par-natives-windows.jar
set sources_path=J:\Programmations\java\eclipse\moteurs\OnsieaEngine2\target\generated_sources\assemble
set destination_path="bin2/"
set main_class="J:\Programmations\java\eclipse\moteurs\OnsieaEngine2\target\generated_sources\assemble/fr/onsiea/engine/game/GameTest.java"

set java_path=C:\Program Files\Java\jdk-19\
set javac_exe="%java_path%\bin\javac.exe"
set delombok=-jar "%lib_path%\archives\Lombok\lombok-1.18.26.jar" delombok
set processor=--processor-module-path "%lib_path%\archives\Lombok\lombok-1.18.26.jar" -proc:only
set print=-verbose -Xlint -J-verbose -g

%javac_exe% %main_class% -sourcepath "%sources_path%" -encoding UTF-8 %print% -d %destination_path% -implicit:class --module-path "%modules_path%" -classpath "%classes_path%"