@echo off
set CLIENT=sources/client/fr/onsiea/engine/client/
set GRAPHICS=sources/client/fr/onsiea/engine/client/graphics/
set OPENGL=sources/client/fr/onsiea/engine/client/graphics/OPENGL/
set VULKAN=sources/client/fr/onsiea/engine/client/graphics/VULKAN/
set INPUT=sources/client/fr/onsiea/engine/client/input/
set COMMON=sources/common/fr/onsiea/engine/common/
set CORE=sources/core/fr/onsiea/engine/core/
set GAME=sources/game/fr/onsiea/engine/game/
set SERVER=sources/server/fr/onsiea/engine/server/
set UTILS=sources/utils/fr/onsiea/engine/utils/
set RESOURCES=resources/
@echo on