package fr.onsiea.engine.client.input;

public enum ActionTypes
{
	JUST_PRESSED, PRESSED, PRESSED_FOR_WHILE, JUST_REPEATED, REPEATED, REPEATED_FOR_WHILE, JUST_RELEASED, RELEASED,
	RELEASED_FOR_WHILE, UNKNOWN;
}
